### PR TITLE
Replaced all string numbers with actual numbers

### PR DESCRIPTION
**Pull request by stocky37**
As found in [this](https://www.reddit.com/r/EpicSeven/comments/atb6wf/another_equipment_preview_tool/eh155nf) reddit comment XD

### CODE REVIEW

**Comment by kmalone86** [comment]
Values look fine. Looks like that annoying formatting change issue is still in. All the lists got moved to 1 line.

**Comment by stocky37** [comment]
Woops, I'll fix it up!

**Comment by stocky37** [comment]
Looks like those formatting issues are being added by your prettier git hook. Do you still want me to recommit without the hook running?

**Comment by kmalone86** [comment]
The issues happened as "prettier" option is forced to run on "git commit", which auto fixes all the modified files to be this way.  The only way I know to get around it, if Raphael hasn't fix, is to add "--print-width 10" argument to 

package.json
        "prettier:json": "prettier --print-width 10 --write \"**/*.json\"",

**Comment by stocky37** [comment]
I know, I was just wondering if you wanted me to bypass the hook or not since the point of a `prettier` hook is to keep formatting consistent XD

Also FYI, you can ignore hooks from running when committing with the `--no-verify` option when running `git commit`.

**Comment by kmalone86** [comment]
Good to know lol

**Comment by stocky37** [comment]
So should I redo it without running the hook, or leave it as-is?

(Sorry, it's 4am I really need to go to bed XD)

**Comment by kmalone86** [comment]
Go to bed, I will ask Raphael and fix if needed.

**Comment by stocky37** [comment]
Haha ok, cheers!

**Pull request merged**
