### PR TITLE
Added lv50FiveStarFullyAwakened stat field

### PR DESCRIPTION
**Pull request by kmalone86**
Many of the max5 and max6 stats were in random order due to script used to add. The first commit fixes this order, so they are all synced.

Second commit adds lv50FiveStarFullyAwakened field to all heroes and copies their max5 values as they are 70% the same.

Edit: In order to help speed it up, modified script to automatically add awakening bonuses to stats for 5* awakened. Every hero I have checked is correct. The CP still needs to be updated for everyone as I do not know how to calculate that.

Tweaked the order of of stats to base, 5star, 5starAwake, 6star, 6starAwake  as there appeared to be a bunch of different orders. Not harmful, but makes easier to read across files.

### CODE REVIEW

**Comment by RaphaelDDL** [comment]
Can you run your script then to keep CP as 0? That would be a better way of reminding us to fix rather than having a wrong number. Is it possible?

**Comment by kmalone86** [comment]
@RaphaelDDL They should already be in that state. (from f60b57b commit)

"lv50FiveStarFullyAwakened": {
            "cp": 0,
            "atk": 484,
....

**Comment by RaphaelDDL** [comment]
doh, was reading the previous commit rather than latest changes :(

**Comment by stocky37** [comment]
I've been thinking, is there even any point in having the awakened versions of the stat fields if it can be calculated from the base stats + the awakening field? In my app I've just been doing that so I have no use for the other fields anyway so it doesn't affect me but thought I'd add my 2c anyway :)

**Comment by kmalone86** [comment]
@stocky37  Ideally this is true, which is how I updated the stats. Though it isn't harmful to have the data. Personally I don't know how the cp is calculated, but I am sure someone does. Game likes to hide there decimal values (displays as rounded down), so may cause issues later(I know this made calculating some of the imprints a bit weird as rounded hidden values were used).  I would hope it isn't taxing on server to calculate, but I haven't looked at the apis or what the bot uses, so not really sure.

**Comment by stocky37** [comment]
@kmalone86 I haven't been able to find anyone that knows how the CP is calculated. I had a poor attempt at it and got as far as the following: [stocky37/epicseven-tools#38](https://github.com/stocky37/epicseven-tools/issues/38#issuecomment-455775717), but didn't spend much time or make much progress XD

**Comment by kmalone86** [comment]
I can't really expect others to fully review the automated changes. Did a self review and not glaring reason seen not to merge.

**Pull request merged**
