### PR TITLE
added gameId to all heroes

### PR DESCRIPTION
**Pull request by RaphaelDDL**
WIP
All added, except generic nat3 ones TODO

Also:
- fixed Tieria skill 3, which was pre-nerf
- removed double description from Tamarinne's skills, now only the applicable description is shown on each of her 5 skills

### CODE REVIEW

**Comment by kmalone86** [comment]
Looks like the dogs are breaking your build as they don't have gameIds.

The reason Tamarinne has both skills in description is due to that is how in-game shows it. In combat, the full description of both versions are shown, no matter what form you are in.

screenshot_20190225-142646_epic seven

screenshot_20190225-142707_epic seven

**Comment by RaphaelDDL** [comment]
I updated the validationRules for the gameId so I would know who is missing. 
I haven't add the gameId on almost any nat3, that's why is breaking (and why I added `wip` :P). 

For Tamarinne, while looks like this in game, won't it look better on the DB to actually only show the proper? I mean, even SW devs weren't as lazy as writing description twice when they implemented Unicorns (which transform into other skill set, like Tama). Idk, for DB looks better since they have their own tabs.

**Comment by RaphaelDDL** [comment]
ok, done @kmalone86

**Comment by kmalone86** [comment]
@RaphaelDDL  not sure why but some of the files got converted from 4-space tabs to 2-space tabs. It looks to only be the new 3\* changes. I thought the prettier was setup to do 4-space?

**Comment by RaphaelDDL** [comment]
@kmalone86 Let me check, sec.

**Comment by RaphaelDDL** [comment]
ok, fixed json prettierrc and re prettify all, 4 space are back.

**Pull request merged**
