### PR TITLE
October 16 2019 patch

### PR DESCRIPTION
**Pull request by kmalone86**
Still missing a lot of information on new 3* heroes as patch notes only talks about skills.

### CODE REVIEW

**Comment by kmalone86** [comment]
I believe that is all the data I can add for now.

Don't have camping data and gameIds are not listed in spreadsheet yet. Only got 1 from summons, so missing summon message for other 4.

**Comment by RaphaelDDL** [comment]
I got the assets from Dim, will add the gameIds when I see in-game whose face's are to which name haha

**Comment by kmalone86** [comment]
Great, found out after my comment above that there was a datamine too, so will have to add that when I get a chance.

**Comment by kmalone86** [comment]
That should be everything.

Missing the gameIds as mentioned before.

Preview missing ML Crozet stats (no comparable existing hero), Specialty Skill description, cnd/charm/politics, and relationships.
preview artifact missing stats.

**Pull request merged**
