### PR TITLE
Map json directories under `./src` automatically

### PR DESCRIPTION
**Pull request by stocky37**
I've been playing around with this repo myself locally using `json-server` to serve myself up an API based off the data built here. I've been wanting to add new sets of data and thought it might be easier if new directories were picked up automatically instead of having to add them every time.

I'm not sure if you care about this functionality but I thought I'd put a PR in anyway just in case you might find it useful.

### CODE REVIEW

**Comment by RaphaelDDL** [comment]
I used to have `src` folder but I took the folders out since there's no need to, the project isn't "runnable". 

When you say 

> Thought it might be easier if new directories were picked up automatically instead of having to add them every time.

There's no need for other folders right, from what I can think of at the moment. Though yes, in the future, might need to add more (monsters, guardians, etc).

Anyway, I use `npm run build` to generate the `dist` folder with the json folders then I import those into a `mongodb` database with `mongoimport` using the flag `--jsonArray`. 

For the API, there's another project, at [EpicSevenDB/apiserver](https://github.com/EpicSevenDB/apiserver) which serves the data. Though yes, `json-server` is easier for local dev.

I'll checkout your branch just to check it out but seems like an ok change to go back to `src`. There's no real reason to, other than making easier not having to declare which folder to build on both build and validate.

Gimme a few.

**Comment by stocky37** [comment]
> It used to have src folder but I took the folders out since there's no need to, the project isn't "runnable".

Yep, I had figured as much. The only reason I added one back in was to make it easier to just find all the subdirs and build from there.

> We might need to pull latest on your branch, I added a file on the glob excludes but it's not there on yours. But minor thing.

No worries, let me know if you decide you want to bother with this PR at all and if you decide to I'll merge it in and fix up a few more little things I noticed (there's changes to a few files in here that I didn't intend to include like line endings changes).

Like I said I only really added it because I was using it in this way since I've been adding some extra data endpoints for my own use. IAssuming this repo is used as your source of truth at least that way the data will stay in sync between them :).

The enpoints/datasets I've added so far have just been  (endpoints like `/stats`, `/equipment` etc.) that describe more information around those kinds of things so I can do more stuff programmatically.

**Comment by RaphaelDDL** [comment]
Just an update, I'm thinking on the possibility to make it multi-lang, so I might move all code to `/src/en/` instead, for when we get other langs. But I didn't forget this. 

Just pondering while I'm still coding the website.

**Comment by stocky37** [comment]
Oh, cool I didn't realise this was going to get merged. Thanks! :)

**Comment by RaphaelDDL** [comment]
Thanks.
Funny, I've set travis CI config to use node_js 8, so idk why is passing since on 8 and 9, `isDirectory()` was supposed to break the `npm test` with `TypeError: f.isDirectory is not a function`.

Well, I've updated anyway to have it use 10.15.0

**Pull request merged**
