### PR TITLE
March 27 2019 patch

### PR DESCRIPTION
**Pull request by kmalone86**
Notes:
Sira-Ren had "(One from Decreased Attack, Decreased Hit Chance, Silence, Sleep, and Poison)", but usually () are not included, so need to check post patch.

ml cidds new enhancements were not in usual format in patch notes for +CR, so need to validate how they look in-game. Copied from Diene's CR enhancements for now.

Molagora changes values are not shown in patch notes, need to wait for release.

### CODE REVIEW

**Comment by RaphaelDDL** [comment]
Sira and Justice for All now have the `()` values in game at jornal, so we can add them.

See https://imgur.com/umRv1Wr from https://github.com/EpicSevenDB/ui/issues/18

**Comment by kmalone86** [comment]
They are so long, Dim will have fun displaying them.

**Comment by kmalone86** [comment]
I believe this is everything now.

**Comment by kmalone86** [comment]
Self review, I think it is ok.

**Pull request merged**
