### PR TITLE
Wanda Hero

### PR DESCRIPTION
**Pull request by rapvil**
Left the skill upgrade costs blank, will update them as/if I ever raise her... she seems to be a pretty strong stunner with all her upgrades :O maybe pvp?

### CODE REVIEW

**Comment by rapvil** [comment]
also commit e4fed50 was just updating my fork with the main repo...

**Comment by rapvil** [comment]
thanks for the corrections @kmalone86 ... looks like I wasn't thorough enough :(

Are you happy for me to commit the suggestions so it can just be merged? (Obv, I can't do it myself)

For the  skills, I do have her in game but I can only see the next enhancement's requirements and nothing past... Is the basis of determining the material cost set? I noticed Diene had skill upgrades that were outside the post that was outlined in a previous issue.

**Comment by kmalone86** [comment]
@rapvil It happens, we all make mistakes, except Triharder-E7, somehow they never do.

You can commit the changes any way you want. I am not 100% sure I am using the suggestion tool right, as I got some where I could just accept and it auto-committed them to PR, which make it easy. I can't tell if that is what you are getting or not.

In the skill level up screen, you see a list of all the bonuses for a specific skill on left(after clicking a skill), if you click and hold on one of those bonuses, a window will pop up with what is needed.  I made a wiki for figuring out the resources. I just compared it to Diene(have her) and it does match the wiki, though found a mistake(in Max skill level: 7).
screenshot_2018-12-03-18-50-05

**Comment by rapvil** [comment]
I've accepted the commits... did not know Github had that feature lol @kmalone86 yikes that did a whole bunch of commits lol I'll check the wiki for future references and will update the commits i've done wit the skill enhancement requirements.. thank you

**Pull request merged**
